import React from "react";

//metadata
export const metadata = {
  title: "About page",
  description: "Generated by create next app",
};
const page = () => {
  // throw new Error("Something went wrong");
  
  return (
    <div className="mt-4">
      <p>This is about page</p>
    </div>
  );
};

export default page;
